apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-api
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: rating-api

  template:
    metadata:
      labels:
        app: rating-api

    spec:
      containers:
      - name: rating-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 5000