apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault-secrets
  namespace: devapp

spec:
  provider: azure

  secretObjects:
  - secretName: mongodb-secret
    type: Opaque

    data:
    - objectName: mongourl
      key: MONGO_URL

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: "1b9df903-5240-4baf-b3cc-7058c401bb91"

    keyvaultName: "aks-key-vault-niyati"

    tenantId: "8989600b-fe48-4de4-a882-e285f8ee680c"

    objects: |
      array:
        - |
          objectName: mongourl
          objectType: secret